# Generated by Django 5.1.3 on 2025-01-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('candidate_email', models.CharField(max_length=50)),
                ('candidate_password', models.CharField(max_length=50)),
            ],
        ),
    ]
