# Generated by Django 5.1.3 on 2025-01-30 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_name', models.CharField(max_length=50)),
                ('examination_mark', models.CharField(max_length=50)),
                ('examination_qno', models.CharField(max_length=50)),
                ('examination_time', models.CharField(max_length=50)),
            ],
        ),
    ]
