# Generated by Django 5.1.3 on 2025-01-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0002_tbl_examination'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
            ],
        ),
    ]
