# Generated by Django 5.1.3 on 2025-01-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0003_tbl_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_questions',
        ),
    ]
