# Generated by Django 5.1.3 on 2025-01-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0004_delete_tbl_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('exam_id', models.CharField(max_length=100)),
            ],
        ),
    ]
