# Generated by Django 5.1.3 on 2025-01-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0006_tbl_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_options',
        ),
        migrations.DeleteModel(
            name='tbl_questions',
        ),
    ]
