# Generated by Django 5.1.3 on 2025-01-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0007_delete_tbl_options_delete_tbl_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cordinator.tbl_examination')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cordinator.tbl_questions')),
            ],
        ),
    ]
