# Generated by Django 5.1.3 on 2025-02-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0008_tbl_questions_tbl_options'),
        ('Guest', '0004_tbl_cordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_examination',
            name='cordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_cordinator'),
        ),
    ]
