# Generated by Django 5.1.6 on 2025-03-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0009_tbl_examination_cordinator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_options',
        ),
    ]
