# Generated by Django 5.1.6 on 2025-03-02 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0010_delete_tbl_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cordinator.tbl_questions')),
            ],
        ),
    ]
