# Generated by Django 5.1.6 on 2025-03-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0011_tbl_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_examination',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
