# Generated by Django 5.1.6 on 2025-03-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0012_tbl_examination_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_examination',
            name='examination_status',
            field=models.IntegerField(default=0),
        ),
    ]
