# Generated by Django 5.1.6 on 2025-03-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0013_tbl_examination_examination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_examination',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
