# Generated by Django 5.1.6 on 2025-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cordinator', '0014_tbl_examination_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_examination',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
