# Generated by Django 5.1.3 on 2025-01-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cordinator_name', models.CharField(max_length=50)),
                ('cordinator_contact', models.CharField(max_length=50)),
                ('cordinator_email', models.CharField(max_length=50)),
                ('cordinator_password', models.CharField(max_length=50)),
            ],
        ),
    ]
