# Generated by Django 5.1.6 on 2025-03-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cordinator', '0011_tbl_options'),
        ('Guest', '0004_tbl_cordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examinationbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.CharField(max_length=30)),
                ('examinationbody_status', models.IntegerField(default=0)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cordinator.tbl_examination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_examinationanswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinationanswers_statusq', models.IntegerField(default=0)),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='Cordinator.tbl_options')),
                ('myanswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myanswer', to='Cordinator.tbl_options')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cordinator.tbl_questions')),
                ('examinationbody', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_examinationbody')),
            ],
        ),
    ]
