# Generated by Django 5.1.6 on 2025-03-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_tbl_examinationanswers_myanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_examinationbody',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
    ]
